module.exports = {
  globals: {
    Atomics: "readonly",
    SharedArrayBuffer: "readonly",
    SimpleRecord: "readonly",
    SimpleApiRequest: "readonly",
    SimpleApiResponse: "readonly",
    SimpleImage: "readonly",
    SimpleAttachment: "readonly",
    SimpleAttachmentService: "readonly",
    SimpleCache: "readonly",
    SimpleDateTime: "readonly",
    SimpleDuration: "readonly",
    SimpleEmailOutbound: "readonly",
    SimpleEmailTemplate: "readonly",
    SimpleEngine: "readonly",
    SimpleImport: "readonly",
    SimpleLogArchive: "readonly",
    SimpleMail: "readonly",
    SimpleMessage: "readonly",
    SimpleRecordDeletionLog: "readonly",
    SimpleRestRequest: "readonly",
    SimpleRestResponse: "readonly",
    SimpleSearch: "readonly",
    SimpleSchedule: "readonly",
    SimpleSession: "readonly",
    SimpleSystem: "readonly",
    SimpleTable: "readonly",
    SimpleTemplate: "readonly",
    SimpleTemplatePrinter: "readonly",
    SimpleTime: "readonly",
    SimpleUser: "readonly",
    SimpleUserCriteria: "readonly",
    SimpleVcs: "readonly",
    SimpleAjax: "readonly",
    SimpleEventBus: "readonly",
    SimpleForm: "readonly",
    SimpleGo: "readonly",
    SimpleList: "readonly",
    SimpleMenu: "readonly",
    SimpleModal: "readonly",
    SimplePreference: "readonly",
    SimpleStorage: "readonly",
    SimpleWidget: "readonly",
    s_i18n: "readonly",
    s_user: "readonly",
    s_widget: "readonly",
    s_widgets: "readonly",
    s_widget_custom: "readonly",
    s_go: "readonly",
    data: "readonly",
    input: "readonly",
    URL: "readonly",
    location: "readonly",
    history: "readonly",
    options: "readonly",
    ss: "readonly",
  },

  rules: {
    camelcase: [
      "error",
      { properties: "never", ignoreGlobals: true, allow: ["s_widget_custom"] },
    ],
    "node/no-unsupported-features/node-builtins": [
      "error",
      {
        version: ">=12.0.0",
        ignores: [],
      },
    ],
  },
};
